### ISSUE TITLE
/tc toggle does not work on 1.19 paper

### ISSUE THREAD

**Issue by Mr-KayJayDee** [Cristichi/CrisTreeCapitator#10]
![Screenshot 2022-07-22 at 18 19 53](https://user-images.githubusercontent.com/46600662/180481748-7b9475a7-b12a-4684-83d6-5486e26e7069.png)

When i toggle and go in disabled mode it stills chop entire tree

**Comment by Cristichi** [comment]
I tested it on both 1.19 and 1.19.1 and it seems to be working properly. It seems like you are running on the latest version but still please make sure if it's up to date, because there was some winkyness a few versions back.

Also, I don't think other plugins would interfere with mine, specially making it still work when it is toggled, so I honestly don't know what could be happening.

**Comment by Mr-KayJayDee** [comment]
I dug a bit into it and it think I had some others plugins that had a treechop enabled by default which I guess made some troubles 🤔

**Comment by Cristichi** [comment]
I'm so glad you could fix it!

By the way I realised, checking the code, that I failed to remember to update /tc help and /tc values (which I renamed to /tc settings while I was at it) so thank you anyway!

Lord I always forget to change help and values when I add new commands....
