### ISSUE TITLE
Overwriting crouch_for_prevention and ignore_leaves after server restart

### ISSUE THREAD

**Issue by vaskolukas** [Cristichi/CrisTreeCapitator#12]
Hi, I have problem that two of config options are overwriten to default after server restart.

Options:

`crouch for prevention` is changed to `false`
`ignore leaves` is changed to `false`

Issue:

When I set this two options to true, I hit restart server to apply changes. Everything is good. Options are set correctly. When the server restarts again (automatic or manual restart, doesnt matter) this two options are overwriten to default ignoring my previous set up.

Other options keeps same as I want.

My config: [https://pastebin.com/KELsHtAS](https://pastebin.com/KELsHtAS)
Using version: v6.3.1
Server: Paper 1.19.1

**Comment by Cristichi** [comment]
I shall look into it today, thank you!

**Comment by Cristichi** [comment]
I think there is some problem actually saving the values into the file. When it goes looking for the values inside the file (which should be updated as well when you use commands to change config values) it doesn't find those values, because they are not there for some wicked reason, and therefore assigns them the default value. I'll debugging how it happens right now

**Comment by Cristichi** [comment]
Nevermind, my whole bad. It is fixed on 6.3.3, please update as soon as you see the notification in-game. Have a nice day and many, many thanks for opening the issue!
