### ISSUE TITLE
TreeCapitator decimate whole dark oak forests

### ISSUE THREAD

**Issue by burdoto** [Cristichi/CrisTreeCapitator#2]
An user on my server happened to have a base between the woods of a dark oak forest. When another user came and tried to mine a single tree, the whole forest got capitated by the plugin, as seen in the images:

![unknown-1](https://user-images.githubusercontent.com/42473485/55850966-feb37680-5b56-11e9-8dff-e2ae31afc7e9.png)

![unknown-3](https://user-images.githubusercontent.com/42473485/55851171-e3953680-5b57-11e9-9aa8-57964581f0ff.png)

![unknown-2](https://user-images.githubusercontent.com/42473485/55851201-f9a2f700-5b57-11e9-9374-42528cc6d03d.png)

**Comment by VoidsShadow** [comment]
This would require a new search algorithm to guess where one tree ends and where another begins.

**Comment by burdoto** [comment]
Well, it looks like the current solution just looks for adjacent tree blocks, and never stops, which is a really poor implementation.

**Comment by VoidsShadow** [comment]
Indeed. I thought it would be a good idea to separate my arboretum from a village by planting the trees underground. Due to the way one of the trees grew and how this plugin calculates tree-logs, I decimated half the village.

 My friends were also having issues with accidentally chopping their log houses down and then being unable to break the saplings. Cristichi had protected saplings as an unfinished feature which I wish was disabled by default. Unfortunately, there's no way to disable it without also disabling replanting.

**Comment by burdoto** [comment]
i might make my own tree capitator plugin at some point, if this issue still consists once that's done, i will talk back to you
